### ISSUE TITLE
Lambda Test function failed

### ISSUE THREAD

**Issue by john-leger** [vidanov/lambda-nodejs-lightsail-backup#11]
Though the function failed the image was created.  Any ideas

Response:
{
  "errorMessage": "RequestId: 9bd217be-d09d-11e8-958e-990464706b8e Process exited before completing request"
}

Request ID:
"9bd217be-d09d-11e8-958e-990464706b8e"

Function Logs:
START RequestId: 9bd217be-d09d-11e8-958e-990464706b8e Version: $LATEST
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	KW of year: 42
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	day of year:288
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	day of month:15
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	day of week:1
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	month:9
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	backupDaysNR:1
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	backupWeeksNR:2
2018-10-15T17:13:18.142Z	9bd217be-d09d-11e8-958e-990464706b8e	backupMonthsNR:0
2018-10-15T17:13:18.761Z	9bd217be-d09d-11e8-958e-990464706b8e	instanceName: CentOS-32GB-Virginia-1
2018-10-15T17:13:18.761Z	9bd217be-d09d-11e8-958e-990464706b8e	instanceRegion: us-east-1
2018-10-15T17:13:18.761Z	9bd217be-d09d-11e8-958e-990464706b8e	instanceLabel: LightSail-32GB_
2018-10-15T17:13:19.121Z	9bd217be-d09d-11e8-958e-990464706b8e	No snapshot, we create a new one
2018-10-15T17:13:19.197Z	9bd217be-d09d-11e8-958e-990464706b8e	TypeError: this.deleteInstanceSnapshot is not a function
    at Response.getSnapshots (/var/task/index.js:112:10)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
END RequestId: 9bd217be-d09d-11e8-958e-990464706b8e
REPORT RequestId: 9bd217be-d09d-11e8-958e-990464706b8e	Duration: 1115.28 ms	Billed Duration: 1200 ms 	Memory Size: 512 MB	Max Memory Used: 30 MB	
RequestId: 9bd217be-d09d-11e8-958e-990464706b8e Process exited before completing request

**Comment by vidanov** [comment]
Hi! It seems to be the issue with the first backup. How does it work now? Do you have errors with it?

**Comment by john-leger** [comment]
You are correct.  It is working.
