### ISSUE TITLE
No errors in the test, but no snapshot.

### ISSUE THREAD

**Issue by nessunohastonick** [vidanov/lambda-nodejs-lightsail-backup#12]
Hi, I followed your guide, and the test works as well. But the next morning I do not automatically generate any shapshot. Are there any steps? Thank you.

**Comment by vidanov** [comment]
Hi! Did you the trigger for Cloud Watch Events?

In the panel Add triggers at the left click the CLOUD WATCH EVENTS link. In the 'Rule' section select 'Create a new rule'. Give the name daily in the 'Schedule expression' section put rate(1 day) and push the ADD button.﻿

**Comment by nessunohastonick** [comment]
Hi, yes, I had inserted it. Everything works.
I expected the backup to be generated at midnight, instead they are generated at the same time I do the test, is there a way to change this behavior?

**Comment by nessunohastonick** [comment]
Now it does not work anymore, I receive the following error message:
`
START RequestId: e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8 Version: $LATEST
2018-10-26T07:51:06.682Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	KW of year: 43
2018-10-26T07:51:06.682Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	day of year:299
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	day of month:26
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	day of week:5
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	month:9
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	backupDaysNR:5
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	backupWeeksNR:3
2018-10-26T07:51:06.683Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	backupMonthsNR:0
2018-10-26T07:51:09.001Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	instanceName: Plesk_Hosting_Stack_on_Ubuntu-4GB-Frankfurt-1
2018-10-26T07:51:09.001Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	instanceRegion: eu-central-1
2018-10-26T07:51:09.001Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	instanceLabel: Bunny1
2018-10-26T07:51:09.863Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	No snapshot, we create a new one
2018-10-26T07:51:10.163Z	e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	TypeError: this.deleteInstanceSnapshot is not a function
    at Response.getSnapshots (/var/task/index.js:112:10)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
END RequestId: e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8
REPORT RequestId: e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8	Duration: 3585.99 ms	Billed Duration: 3600 ms 	Memory Size: 128 MB	Max Memory Used: 60 MB	
RequestId: e4b7e708-d8f3-11e8-bfd3-fb5ed0a83ca8 Process exited before completing request
`

The only change I made was to upgrade a 2gb ram instance to a 4gb instance.
Obviously I changed the instance name in the code

**Comment by vidanov** [comment]
It seems to be the problem with the script execution. Did you set 6.10 for NodeJS? http://take.ms/nxwa4

**Comment by vidanov** [comment]
>> The only change I made was to upgrade a 2gb ram instance to a 4gb instance.

Did you change the instance name? It should be new I suppose.

**Comment by vidanov** [comment]
>I expected the backup to be generated at midnight, instead they are generated at the same time I do the test, is there a way to change this behavior?

Yes, you can set up the cloud watch trigger in cron style instead 
rate(1 day)
put
cron(0 0 * * *)

http://take.ms/7d4kY

**Comment by vidanov** [comment]
>The only change I made was to upgrade a 2gb ram instance to a 4gb instance.
Obviously I changed the instance name in the code

You have an issue with the first one snapshot. It should work with the second one without errors.

**Comment by nessunohastonick** [comment]
> 
> 
> > The only change I made was to upgrade a 2gb ram instance to a 4gb instance.
> > Obviously I changed the instance name in the code
> 
> You have an issue with the first one snapshot. It should work with the second one without errors.

I tried to create a totally new instance, and I replaced it in the code

```
const instances = [
{name: "CentOS-512MB-Frankfurt-1", region: "eu-central-1", label: "Bunny1"}
];
```

but I receive the same error: TypeError: this.deleteInstanceSnapshot is not a function

**Comment by nessunohastonick** [comment]
> cron(0 0 * * *)

If I try that, I receive the following error message:

   Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 0dbabb9d-d907-11e8-82ab-77f3f9e9752f)

**Comment by vidanov** [comment]
Sorry for that!

Try this one:

cron(0 0 * * ? *)

**Comment by nessunohastonick** [comment]
> cron(0 0 * * ? *)

Yes! Now it accepts the rule, thank you

**Comment by nessunohastonick** [comment]
I found the problem:
I had to delete the previous instance snapshots generated by the lambda function, now it works! thanks anyway.
