### ISSUE TITLE
this.deleteInstanceSnapshot is not a function

### ISSUE THREAD

**Issue by donnell5000** [vidanov/lambda-nodejs-lightsail-backup#15]
When I run the code, I get the error below.  Any ideas what may cause this.

Thank you.

TypeError: this.deleteInstanceSnapshot is not a function
at Response.getSnapshots (/var/task/index.js:113:10)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)

**Comment by maxwoerner** [comment]
Unfortunately, I get the same error. Any idea how to fix this?

**Comment by donnell5000** [comment]
Sorry, no, still waiting for an answer.  
I'm not sure it would work anyway even without the error since I am forced to stop the instance before creating a snapshot when doing it manually.
Hopefully someone has a solution.

**Comment by vidanov** [comment]
I restored the working version of the script. Please try it now, get the current code.  Sorry for the inconvenience.

**Comment by donnell5000** [comment]
It's working again, thank you.
