### ISSUE TITLE
Inaccessible host: `lightsail.eu-west-2a.amazonaws.com'

### ISSUE THREAD

**Issue by codecomp** [vidanov/lambda-nodejs-lightsail-backup#25]
I tried to set this up a while back with an older version without any luck but setup it up again with the latest version but I'm getting the following issue.

Made a new LS instance called Test and got the region from it, set this up to run Friday over the weekend but it's not making instances. I've not changed any settings Other than adding in the instance name and the region and not done anything with this AWS account so I"m unsure what the cause could be.

![Screen Shot 2019-11-04 at 10 25 06](https://user-images.githubusercontent.com/7384149/68114249-78dd8b00-feed-11e9-96b7-ecb490e74224.png)

`START RequestId: 8797d976-efaf-4b43-86aa-db433e5008a7 Version: $LATEST
2019-11-03T16:05:20.510Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO KW of year: 44
2019-11-03T16:05:20.511Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO day of year:307
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO day of month:3
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO day of week:0
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO month:10
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO backupDaysNR:0
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO backupWeeksNR:0
2019-11-03T16:05:20.529Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO backupMonatsNR:1
2019-11-03T16:05:21.890Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO no backup, we do it new
2019-11-03T16:05:22.012Z 8797d976-efaf-4b43-86aa-db433e5008a7 INFO { UnknownEndpoint: Inaccessible host: `lightsail.eu-west-2a.amazonaws.com'. This service may not be available in the `eu-west-2a' region.
at Request.ENOTFOUND_ERROR (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:494:46)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at ClientRequest.error (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:333:22)
at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:96:19)
at ClientRequest.emit (events.js:198:13)
at ClientRequest.EventEmitter.emit (domain.js:448:20)
at TLSSocket.socketErrorListener (_http_client.js:392:9)
at TLSSocket.emit (events.js:198:13)
message:
'Inaccessible host: `lightsail.eu-west-2a.amazonaws.com\'. This service may not be available in the `eu-west-2a\' region.',
code: 'UnknownEndpoint',
region: 'eu-west-2a',
hostname: 'lightsail.eu-west-2a.amazonaws.com',
retryable: true,
originalError:
{ Error: getaddrinfo ENOTFOUND lightsail.eu-west-2a.amazonaws.com lightsail.eu-west-2a.amazonaws.com:443
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
message:
'getaddrinfo ENOTFOUND lightsail.eu-west-2a.amazonaws.com lightsail.eu-west-2a.amazonaws.com:443',
errno: 'ENOTFOUND',
code: 'NetworkingError',
syscall: 'getaddrinfo',
hostname: 'lightsail.eu-west-2a.amazonaws.com',
host: 'lightsail.eu-west-2a.amazonaws.com',
port: 443,
region: 'eu-west-2a',
retryable: true,
time: 2019-11-03T16:05:22.009Z },
time: 2019-11-03T16:05:22.009Z } 'UnknownEndpoint: Inaccessible host: `lightsail.eu-west-2a.amazonaws.com\'. This service may not be available in the `eu-west-2a\' region.\n at Request.ENOTFOUND_ERROR (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:494:46)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)\n at ClientRequest.error (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:333:22)\n at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:96:19)\n at ClientRequest.emit (events.js:198:13)\n at ClientRequest.EventEmitter.emit (domain.js:448:20)\n at TLSSocket.socketErrorListener (_http_client.js:392:9)\n at TLSSocket.emit (events.js:198:13)'
END RequestId: 8797d976-efaf-4b43-86aa-db433e5008a7
REPORT RequestId: 8797d976-efaf-4b43-86aa-db433e5008a7 Duration: 5795.26 ms Billed Duration: 5800 ms Memory Size: 128 MB Max Memory Used: 94 MB Init Duration: 191.30 ms`
![Screen Shot 2019-11-04 at 10 25 06](https://user-images.githubusercontent.com/7384149/68114230-71b67d00-feed-11e9-8417-fd755c6beabe.png)

**Comment by vidanov** [comment]
Please use 'lightsail.eu-west-2' instead of 'lightsail.eu-west-2a'

**Comment by codecomp** [comment]
Ahh my mistake I seem to have not paid enough attention, thank you. Updated it now and I'll see how it works out tomorrow.
